# USE THIS DOCKER COMPOSE ONLY FOR DEVELOPMENT ON THIS SINGLE SERVICE

version: '3.9'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'python server.py'
        ports: 
            - 5001:5000
        volumes: 
            - .:/app